language: node_js
# nodejs版本
node_js:
  - lts/*

# Start: Build Lifecycle
install:
  - yarn

before_script:

script:
  - yarn docs:build

after_script:
  - cd ./docs/.vuepress/dist
  - echo 'pluto-ui.smallpig.cn' > CNAME
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "feat:travis-ci auto build"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
# End: Build LifeCycle

# 指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
    
env:
  global: